/* 1. Lister tous les membres inscrits : */
SELECT * FROM ADHERENT WHERE 1;

/* 2. Lister tous les livres disponibles : */
SELECT EX.COTELIVRE, EX.NUMEXEMPLAIRE, L.TITRE, L.AUTEUR FROM LIVRE L 
JOIN EXEMPLAIRE EX ON L.COTELIVRE=EX.COTELIVRE 
WHERE (EX.COTELIVRE, EX.NUMEXEMPLAIRE) 
NOT IN (SELECT COTELIVRE, NUMEXEMPLAIRE FROM EMPRUNTER WHERE DATERETOUR IS NULL);

/* 3. Lister les emprunts en cours (non retournés) */
SELECT A.NOM, A.PRENOM, E.NUMEXEMPLAIRE, L.TITRE, L.AUTEUR FROM ADHERENT A 
JOIN EMPRUNTER E ON A.NUMADHERENT = E.NUMADHERENT 
JOIN EXEMPLAIRE EX ON E.NUMEXEMPLAIRE = EX.NUMEXEMPLAIRE AND E.COTELIVRE = EX.COTELIVRE 
JOIN LIVRE L ON EX.COTELIVRE = L.COTELIVRE WHERE E.DATERETOUR IS NULL;

/* 4. Lister les emprunts avec date retour(déjà retourner) */
SELECT * FROM EMPRUNTER WHERE DATERETOUR IS NOT NULL ;

/* 5.a. Affichage des détails d'un membre spécifique */
SELECT * FROM ADHERENT WHERE NUMADHERENT='2/E/2024' ;

/* b. Affichage des membres qui sont des étudiants */
SELECT * FROM ADHERENT WHERE NUMADHERENT REGEXP '.*E.*';

/* c. Affichage des membres qui sont des personnels */
SELECT * FROM ADHERENT WHERE NUMADHERENT REGEXP '.*P.*' ;

/* 6. Détails d'un livre spécifique */
SELECT EX.COTELIVRE, EX.NUMEXEMPLAIRE, L.TITRE, L.AUTEUR, EX.ETAT, L.EXCLUS_DE_PRET
FROM EXEMPLAIRE EX JOIN LIVRE L ON EX.COTELIVRE=L.COTELIVRE
WHERE EX.NUMEXEMPLAIRE=1 AND EX.COTELIVRE='1001/DRO' ;

/* 7. Livres emprunter par un membre donné */
SELECT EX.COTELIVRE, EX.NUMEXEMPLAIRE, L.TITRE, L.AUTEUR, EX.ETAT, A.NUMADHERENT, A.NOM, A.PRENOM  
FROM EMPRUNTER E  JOIN EXEMPLAIRE EX 
ON (EX.NUMEXEMPLAIRE = E.NUMEXEMPLAIRE AND EX.COTELIVRE = E.COTELIVRE) 
JOIN LIVRE L ON EX.COTELIVRE=L.COTELIVRE 
JOIN ADHERENT A ON A.NUMADHERENT = E.NUMADHERENT
WHERE E.NUMADHERENT = '5/E/2024';

/* 8. Afficher les membres qui ont empruntés un livre donnée (livre meme cote)*/
SELECT A.NUMADHERENT, A.NOM, A.PRENOM, A.TEL, E.COTELIVRE, C.DATE_PRET, E.DATERETOUR
FROM EMPRUNTER E JOIN ADHERENT A ON A.NUMADHERENT = E.NUMADHERENT
JOIN CALENDRIER C ON C.DATE_PRET = E.DATE_PRET
WHERE E.COTELIVRE = '1001/DRO' ; 

/* 9. Lister les livres emprunter récement (par période : 2 semaines ) */
SELECT * FROM EMPRUNTER E JOIN CALENDRIER C ON C.DATE_PRET=E.DATE_PRET 
WHERE C.DATE_PRET >= DATE_SUB(CURDATE(), INTERVAL 2 WEEK) AND CURDATE() > C.DATE_PRET;

/* 10. Lister les membres ayant emprunté un livre et non encore retourné */
SELECT A.NUMADHERENT, A.NOM, A.PRENOM FROM ADHERENT A JOIN EMPRUNTER E 
ON A.NUMADHERENT = E.NUMADHERENT WHERE E.DATERETOUR IS NULL;

/* 13. Rechercher les membres inscrits pendant une période spécifique */
SELECT * FROM ADHERENT WHERE DATEADHESION BETWEEN '2024-05-01' AND '2024-07-31';

/* 14. Compter le nombre total des livres dans la bibliothèque */
SELECT COUNT(*) FROM EXEMPLAIRE WHERE 1 ;

/* 15. Compter les emprunts effectués par un membre */
SELECT COUNT(*)
FROM EMPRUNTER E  JOIN EXEMPLAIRE EX 
ON (EX.NUMEXEMPLAIRE = E.NUMEXEMPLAIRE AND EX.COTELIVRE = E.COTELIVRE) 
JOIN LIVRE L ON EX.COTELIVRE=L.COTELIVRE 
JOIN ADHERENT A ON A.NUMADHERENT = E.NUMADHERENT
WHERE E.NUMADHERENT = '5/E/2024';

/* 16. Compter le nombre total d'emprunts pour un livre donné */
SELECT COUNT(*)
FROM LIVRE L JOIN EMPRUNTER E ON L.COTELIVRE = E.COTELIVRE
WHERE L.COTELIVRE = '1001/DRO';

/* Effectuer un nouveau emprunt :*/
INSERT INTO CALENDRIER VALUES(CURDATE());
INSERT INTO EMPRUNTER VALUES('8/E/2024', '6755/MAT',4, CURDATE(), NULL) 
WHERE NOT (SELECT EXCLUS_DE_PRET FROM LIVRE WHERE COTELIVRE='8/E/2024');
/* /ERROR/ */

/* Emprunts en retards*/
SELECT * FROM EMPRUNTER 
WHERE DATE_ADD(DATE_PRET, INTERVAL 2 WEEK) <= CURDATE() AND DATERETOUR IS NULL ;

/* Vérification de la disponibilité d'un livre */
SELECT COUNT(*) FROM EXEMPLAIRE WHERE COTELIVRE = '1001/DRO' 
AND (COTELIVRE, NUMEXEMPLAIRE) NOT IN
(SELECT COTELIVRE, NUMEXEMPLAIRE FROM EMPRUNTER WHERE DATERETOUR IS NULL);

/* 27. Historisation d'emprunts d'un membre */
SELECT A.NOM, A.PRENOM, E.NUMEXEMPLAIRE, L.TITRE, L.AUTEUR, E.DATE_PRET, E.DATERETOUR 
FROM ADHERENT A JOIN EMPRUNTER E ON A.NUMADHERENT = E.NUMADHERENT  
JOIN EXEMPLAIRE EX ON E.NUMEXEMPLAIRE = EX.NUMEXEMPLAIRE AND E.COTELIVRE = EX.COTELIVRE  
JOIN LIVRE L ON EX.COTELIVRE = L.COTELIVRE WHERE E.NUMADHERENT='1/E/2024';
